# Default values for angular-node-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: paulbouwer/hello-kubernetes:1.8
  pullPolicy: Always

application:
  name: hello-kubernetes