apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.application.name}}
spec:
  selector:
    matchLabels:
      name: {{.Values.application.name}}
  template:
    metadata:
      labels:
        name: {{.Values.application.name}}
    spec:
      containers:
        - name: app
          image: {{.values.image.repository}}
          ports:
            - containerPort: 8080