apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Values.application.name}}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  backend:
    serviceName: {{.Values.application.name}}
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{.Values.application.name}}
              servicePort: 80